name: Java CI with Maven
env:
  DOCKER_REGISTRY: 172.16.238.245
  APP_NAME: queue-master
  JFROG_USER: ${{ secrets.JFROG_USER }}
  JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Build the Docker image
      run: docker build . --tag "$DOCKER_REGISTRY/$APP_NAME:1.0.${{ github.run_id }}"
      
    
   # - name: Build the Docker image
    #- uses: actions/checkout@v3
    #  run: docker build . --file Dockerfile --tag queue-master:$(date +%s)  
      
    - uses: actions/checkout@v3    
    - name: jforg login
      uses: jfrog/setup-jfrog-cli@v2
      env:   
       JFROG_USER: ${{ secrets.JFROG_USER }}
       JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
       
   
       
   
    - name: Push to JFrog
      run: docker push "$DOCKER_REGISTRY/$APP_NAME:1.0.${{ github.run_id }}"
      
      
#    - name: Login to DockerHub
#      run: |
#          echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "venupj" --password-stdin 
        
    
#    - name: Push to Docker Hub
#      uses: mr-smithers-excellent/docker-build-push@v5
#      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
#      with:
#       # path: docker/queue-master
#        dockerfile: ./Dockerfile
#        registry: docker.io
#        image: venupj/queue-master
        
        
        
